http:
  - hostname: _default
    features:
      wafEnable: true
      rateLimit:
        requestPerSecond: 100
    routes:
      - path: /hello[\w\-/?=.% ]**
        action: loadbalancer
        backendPoolName: DefaultPool
        https: false
      - path: /healthcheck
        action: string
        response:
          code: 200
          message: ok
https:
  - hostname: _default
    wafEnable: true
    routes:
      - path: /healthcheck
        action: string
        response:
          code: 200
          message: ok
